### ISSUE TITLE
Removing the MakeClickHandler function

### ISSUE THREAD

**Issue by emiliogomezlavin** [mnorelli/tic-tac-toe#2]
I can see why you needed to add this function but it feels as an additional step that is not needed if there was another way of adding the EventListeners. Could you re-think where to assign the eventListeners to avoid having to do this? Could you do it with your divs ids? I did the same thing you did but I believe there's a more effective way to place the event listerners. Let me know if can't find it and I can help as I already refactored mine with this step. It was an interesting challenge :)

**Comment by mnorelli** [comment]
Thanks also for this.  Annabelle gave similar feedback, and you both are great at providing clues, prompting toward an answer without giving it away!  I hope I found the answer you were hinting at!

I had been trying to make nine click events with a loop, so that the click callback would know its own location and pass that as an argument.  Too hard!

Much easier to just make a generic click event, and then query the click event object directly.  Cool!
